---
title: "gitHub"
author: "Bryan Milstead"
date: "Tuesday, March 10, 2015"
output: html_document
---

**https://help.github.com/articles/caching-your-github-password-in-git/**
Run this and gitHub will remember you username and passwords: git config --global credential.helper wincred

* git config --global user.name "YOUR NAME"
* git config --global user.email "YOUR EMAIL ADDRESS"


* Stage all Changed, new, or deleted files
  - git add -A
* Commit staged files
  - git commit -a -m "a message describing what you did"
* push all changes to the Github account
  - git push origin master
  
###change to a different branch
  git checkout "branch"  e.g.,  git checkout gh-pages
  
  
  
## github upstream merge (sync a forked repository)
* make sure you are in the working directory
* open the shell
* the first time you do this you will need to setup the upstream branch (note: change USEPA to the user and LakeTrophicModelling to the repo)
  - get remote -v
  - git remote add upstream https://github.com/USEPA/LakeTrophicModelling
* once you are setup use the following commands to sync the original to upstream then the upstream to the fork master.
  - git checkout master (just in case)
  - git pull (just in case)
  - git remote -v
 
 
  - git fetch upstream 
  - git merge upstream/master
  - git push origin master
  
* to restart an restudio session on kali:
    - open git bash
    - type: "ssh bmilstea@kali.epa.gov"
    - respond to password request
    - type "ps aux | grep rstudio"
    - This will show the active processes in rstudio.  From this find the rstudio process you want to stop.  The number in the second field is the process id. 
    - below is a copy of a response:
      - "bmilstea  99031  0.8  0.8 1210616 556408 ?      Sl   13:25   0:05 /usr/lib/rstudio-server/bin/rsession -u bmilstea --launcher-token 611E93DD"
    - In this case the process id is "99031"
    - to kill it type: "kill -9 99031"
 